-- Profiles table (Linked to Supabase Auth)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  first_name TEXT,
  last_name TEXT,
  phone TEXT,
  city TEXT,
  birth_date DATE,
  birth_place TEXT,
  cv_language TEXT DEFAULT 'Türkçe',
  hobbies TEXT[],
  languages TEXT[],
  associations TEXT[],
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Education table
CREATE TABLE IF NOT EXISTS education (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  school TEXT NOT NULL,
  degree TEXT,
  start_date DATE,
  end_date DATE
);

-- Experience table
CREATE TABLE IF NOT EXISTS experience (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  company TEXT NOT NULL,
  role TEXT,
  description TEXT,
  start_date DATE,
  end_date DATE
);

-- Projects table (Autonomous & Manual)
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  github_repo_id TEXT,
  name TEXT NOT NULL,
  repo_url TEXT,
  is_autonomous BOOLEAN DEFAULT FALSE,
  start_date DATE,
  end_date DATE,
  wakatime_hours INT DEFAULT 0,
  ai_summary TEXT
);

-- Tech Stack Distribution
CREATE TABLE IF NOT EXISTS tech_stacks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  language TEXT NOT NULL,
  percentage INT NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE education ENABLE ROW LEVEL SECURITY;
ALTER TABLE experience ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE tech_stacks ENABLE ROW LEVEL SECURITY;

-- Create Policies
CREATE POLICY "Users can view their own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can view their own education" ON education FOR SELECT USING (profile_id = auth.uid());
CREATE POLICY "Users can manage their own education" ON education FOR ALL USING (profile_id = auth.uid());

CREATE POLICY "Users can view their own experience" ON experience FOR SELECT USING (profile_id = auth.uid());
CREATE POLICY "Users can manage their own experience" ON experience FOR ALL USING (profile_id = auth.uid());

CREATE POLICY "Users can view their own projects" ON projects FOR SELECT USING (profile_id = auth.uid());
CREATE POLICY "Users can manage their own projects" ON projects FOR ALL USING (profile_id = auth.uid());

CREATE POLICY "Users can view their own tech stacks" ON tech_stacks FOR SELECT USING (
  EXISTS (SELECT 1 FROM projects WHERE projects.id = tech_stacks.project_id AND projects.profile_id = auth.uid())
);
