-- Social Media tablosunu oluşturma
CREATE TABLE IF NOT EXISTS public.social_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    platform TEXT NOT NULL,
    url TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS (Row Level Security) Politikaları
ALTER TABLE public.social_media ENABLE ROW LEVEL SECURITY;

-- Kullanıcılar sadece kendi verilerini görebilir
CREATE POLICY "Users can view own social media accounts" 
ON public.social_media FOR SELECT 
USING (auth.uid() = profile_id);

-- Kullanıcılar sadece kendi verilerini ekleyebilir
CREATE POLICY "Users can insert own social media accounts" 
ON public.social_media FOR INSERT 
WITH CHECK (auth.uid() = profile_id);

-- Kullanıcılar sadece kendi verilerini güncelleyebilir
CREATE POLICY "Users can update own social media accounts" 
ON public.social_media FOR UPDATE 
USING (auth.uid() = profile_id);

-- Kullanıcılar sadece kendi verilerini silebilir
CREATE POLICY "Users can delete own social media accounts" 
ON public.social_media FOR DELETE 
USING (auth.uid() = profile_id);
