-- Profiles table (Linked to Supabase Auth)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  first_name TEXT,
  last_name TEXT,
  phone TEXT,
  city TEXT,
  district TEXT,
  email TEXT,
  birth_date DATE,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Education table
CREATE TABLE IF NOT EXISTS education (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  school TEXT NOT NULL,
  degree TEXT,
  start_date DATE,
  end_date DATE,
  sort_order INTEGER DEFAULT 0
);

-- Experience table
CREATE TABLE IF NOT EXISTS experience (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  company TEXT NOT NULL,
  role TEXT,
  description TEXT,
  start_date DATE,
  end_date DATE,
  sort_order INTEGER DEFAULT 0
);

-- Projects table (Autonomous & Manual)
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  github_repo_id TEXT,
  name TEXT NOT NULL,
  repo_url TEXT,
  is_autonomous BOOLEAN DEFAULT FALSE,
  start_date DATE,
  end_date DATE,
  wakatime_hours INT DEFAULT 0,
  ai_summary TEXT,
  scope TEXT,
  description TEXT,
  technologies TEXT,
  sort_order INTEGER DEFAULT 0
);

-- Tech Stack Distribution
CREATE TABLE IF NOT EXISTS tech_stacks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  language TEXT NOT NULL,
  percentage INT NOT NULL
);

-- Courses and Certifications table
CREATE TABLE IF NOT EXISTS courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  issuer TEXT,
  description TEXT,
  sort_order INTEGER DEFAULT 0
);

-- Languages table
CREATE TABLE IF NOT EXISTS languages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  proficiency TEXT,
  sort_order INTEGER DEFAULT 0
);

-- Communities table
CREATE TABLE IF NOT EXISTS communities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  role TEXT,
  start_date DATE,
  end_date DATE,
  sort_order INTEGER DEFAULT 0
);

-- Enable Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE education ENABLE ROW LEVEL SECURITY;
ALTER TABLE experience ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE tech_stacks ENABLE ROW LEVEL SECURITY;
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE languages ENABLE ROW LEVEL SECURITY;
ALTER TABLE communities ENABLE ROW LEVEL SECURITY;

-- Create Policies
-- Profiles
DROP POLICY IF EXISTS "Users can manage their own profile" ON profiles;
CREATE POLICY "Users can manage their own profile" ON profiles FOR ALL USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- Education
DROP POLICY IF EXISTS "Users can view their own education" ON education;
CREATE POLICY "Users can view their own education" ON education FOR SELECT USING (profile_id = auth.uid());
DROP POLICY IF EXISTS "Users can manage their own education" ON education;
CREATE POLICY "Users can manage their own education" ON education FOR ALL USING (profile_id = auth.uid());

-- Experience
DROP POLICY IF EXISTS "Users can view their own experience" ON experience;
CREATE POLICY "Users can view their own experience" ON experience FOR SELECT USING (profile_id = auth.uid());
DROP POLICY IF EXISTS "Users can manage their own experience" ON experience;
CREATE POLICY "Users can manage their own experience" ON experience FOR ALL USING (profile_id = auth.uid());

-- Projects
DROP POLICY IF EXISTS "Users can view their own projects" ON projects;
CREATE POLICY "Users can view their own projects" ON projects FOR SELECT USING (profile_id = auth.uid());
DROP POLICY IF EXISTS "Users can manage their own projects" ON projects;
CREATE POLICY "Users can manage their own projects" ON projects FOR ALL USING (profile_id = auth.uid());

-- Tech Stacks
DROP POLICY IF EXISTS "Users can view their own tech stacks" ON tech_stacks;
CREATE POLICY "Users can view their own tech stacks" ON tech_stacks FOR SELECT USING (
  EXISTS (SELECT 1 FROM projects WHERE projects.id = tech_stacks.project_id AND projects.profile_id = auth.uid())
);

-- Courses
DROP POLICY IF EXISTS "Users can view their own courses" ON courses;
CREATE POLICY "Users can view their own courses" ON courses FOR SELECT USING (profile_id = auth.uid());
DROP POLICY IF EXISTS "Users can manage their own courses" ON courses;
CREATE POLICY "Users can manage their own courses" ON courses FOR ALL USING (profile_id = auth.uid());

-- Languages
DROP POLICY IF EXISTS "Users can view their own languages" ON languages;
CREATE POLICY "Users can view their own languages" ON languages FOR SELECT USING (profile_id = auth.uid());
DROP POLICY IF EXISTS "Users can manage their own languages" ON languages;
CREATE POLICY "Users can manage their own languages" ON languages FOR ALL USING (profile_id = auth.uid());

-- Communities
DROP POLICY IF EXISTS "Users can view their own communities" ON communities;
CREATE POLICY "Users can view their own communities" ON communities FOR SELECT USING (profile_id = auth.uid());
DROP POLICY IF EXISTS "Users can manage their own communities" ON communities;
CREATE POLICY "Users can manage their own communities" ON communities FOR ALL USING (profile_id = auth.uid());

-- Ensure columns exist for existing tables
ALTER TABLE projects ADD COLUMN IF NOT EXISTS scope TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS technologies TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;

ALTER TABLE experience ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
ALTER TABLE education ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;

ALTER TABLE communities ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE communities ADD COLUMN IF NOT EXISTS end_date DATE;


